/* Copyright © 2020 Evgeny Zaytsev <zx_90@mail.ru>
 * 
 * Distributed under the terms of the GNU LGPL v3 license. See accompanying
 * file LICENSE or copy at https://www.gnu.org/licenses/lgpl-3.0.html
*/

#include "core/token_type.h"

const char* kar_token_type_get_name(const KarTokenType type)
{
#define PROCESS_VAL(p) case(KAR_TOKEN_##p): return #p;
	switch(type){
		PROCESS_VAL(UNKNOWN);
		// Первоначальные
		PROCESS_VAL(MODULE);
		PROCESS_VAL(COMMENT);
		PROCESS_VAL(INDENT);
		PROCESS_VAL(SPACE);
		PROCESS_VAL(IDENTIFIER);
		PROCESS_VAL(SIGN);
		PROCESS_VAL(VAL_STRING);
		
		// Значения переменых.
		PROCESS_VAL(VAL_NULL);
		PROCESS_VAL(VAL_TRUE);
		PROCESS_VAL(VAL_FALSE);
		PROCESS_VAL(VAL_INTEGER);
		PROCESS_VAL(VAL_FLOAT);
		
		// Поля
		PROCESS_VAL(FIELD_CONST);
		PROCESS_VAL(FIELD_VAR);
		
		// Простые переменные
		PROCESS_VAL(VAR_BOOL);
		
		PROCESS_VAL(VAR_INTEGER8);
		PROCESS_VAL(VAR_INTEGER16);
		PROCESS_VAL(VAR_INTEGER32);
		PROCESS_VAL(VAR_INTEGER64);
		
		PROCESS_VAL(VAR_UNSIGNED8);
		PROCESS_VAL(VAR_UNSIGNED16);
		PROCESS_VAL(VAR_UNSIGNED32);
		PROCESS_VAL(VAR_UNSIGNED64);
		
		PROCESS_VAL(VAR_FLOAT32);
		PROCESS_VAL(VAR_FLOAT64);
		PROCESS_VAL(VAR_FLOAT80);
		
		PROCESS_VAL(VAR_STRING);
		
		// Составные переменные.
		PROCESS_VAL(ENUMERATION);
		PROCESS_VAL(STRUCTURE);
		PROCESS_VAL(UNION);

		// Знаки
		PROCESS_VAL(SIGN_NULLABLE);
		PROCESS_VAL(SIGN_OPEN_BRACES);
		PROCESS_VAL(SIGN_CLOSE_BRACES);
		PROCESS_VAL(SIGN_GET_FIELD);
		PROCESS_VAL(SIGN_COMMA);
		PROCESS_VAL(SIGN_COLON);
		
		PROCESS_VAL(SIGN_ASSIGN);
		
		PROCESS_VAL(SIGN_PLUS);
		PROCESS_VAL(SIGN_MINUS);
		PROCESS_VAL(SIGN_MUL);
		PROCESS_VAL(SIGN_DIV);
		PROCESS_VAL(SIGN_MOD);
		
		PROCESS_VAL(SIGN_AND);
		PROCESS_VAL(SIGN_OR);
		PROCESS_VAL(SIGN_NOT);
		PROCESS_VAL(SIGN_EQUAL);
		PROCESS_VAL(SIGN_GREATER);
		PROCESS_VAL(SIGN_LESS);
		
		PROCESS_VAL(SIGN_BIT_AND);
		PROCESS_VAL(SIGN_BIT_OR);
		PROCESS_VAL(SIGN_BIT_NOT);
		PROCESS_VAL(SIGN_BIT_XOR);
		
		// Управление последовательостью выполенения.
		PROCESS_VAL(COMMAND_BLOCK);
		PROCESS_VAL(COMMAND_PASS);
		
		PROCESS_VAL(COMMAND_IF);
		PROCESS_VAL(COMMANT_THEN);
		PROCESS_VAL(COMMAND_ELSE);
		
		PROCESS_VAL(COMMAND_FOR);
		PROCESS_VAL(COMMAND_FROM);
		PROCESS_VAL(COMMAND_TO);
		PROCESS_VAL(COMMAND_STEP);
		
		PROCESS_VAL(COMMAND_FOREACH);
		PROCESS_VAL(COMMAND_GET);
		
		PROCESS_VAL(COMMAND_WHILE);

		PROCESS_VAL(COMMAND_CONTINUE);
		PROCESS_VAL(COMMAND_BREAK);
		
		PROCESS_VAL(COMMAND_OPEN);
		
		PROCESS_VAL(BLOCK_BODY);
		
		// Функция.
		PROCESS_VAL(FUNCTION);
		PROCESS_VAL(FUNC_MODIFIER);
		//PROCESS_VAL(FUNC_PRIVATE);
		//PROCESS_VAL(FUNC_PROTECTED);
		//PROCESS_VAL(FUNC_PUBLIC);
		//PROCESS_VAL(FUNC_LOCAL);
		PROCESS_VAL(FUNC_STAT);
		
		PROCESS_VAL(FUNC_PARAMETERS);
		//PROCESS_VAL(ARGUMENT_CONST);
		//PROCESS_VAL(ARGUMENT_VAR);
		//PROCESS_VAL(ARGUMENT_POINTER);
		
		PROCESS_VAL(FUNC_RETURN_TYPE);
		PROCESS_VAL(FUNC_RETURN);
		
		// Класс
		
		// Шаблон класса
		
		// Тест
		PROCESS_VAL(TEST);
		PROCESS_VAL(CHECK);
	}
#undef PROCESS_VAL
	return "[UNKNOWN]";
}
